// The contribution form: four kinds, one page, one endpoint.
//
// Every rule enforced here is a rule the server enforces too. This is not the security
// boundary and does not pretend to be one; api/_lib/proposals.js validates everything
// again, and would still refuse a hostile payload with this file deleted. What this
// buys is that someone learns a rule while typing rather than after submitting, which
// matters most for editorial rule 4: a grade above "claimed" needs a research source,
// and discovering that from a rejection is a bad way to find out.
//
// The vocabulary block below is generated by scripts/build-site.py from data/vocab.json,
// the same way app.js's is. The selects themselves are pre-rendered in contribute.html,
// so the form is complete before this file runs.
(function () {
/*VOCAB:START*/
const VER = [{slug:"formal",label:"Formally verified",short:"machine-checked proof (e.g. Lean)"},{slug:"independent",label:"Independently checked",short:"checked by third parties who were not the authors"},{slug:"peer-reviewed",label:"Peer reviewed",short:"published after peer review"},{slug:"author-verified",label:"Author verified",short:"verified only by the people who produced it"},{slug:"claimed",label:"Claimed",short:"announced, not independently verified"},{slug:"disputed",label:"Disputed",short:"substantive public challenge to the result"},{slug:"known",label:"Already known",short:"correct, but the result already existed in the literature"},{slug:"refuted",label:"Refuted",short:"shown to be wrong"}];
const AUT = [{slug:"autonomous",label:"Autonomous",short:"the AI did it without human problem-setting or steering"},{slug:"ai-led",label:"AI-led",short:"the AI produced the core idea; humans framed or checked it"},{slug:"collaborative",label:"Collaborative",short:"genuine back-and-forth between AI and human"},{slug:"ai-assisted",label:"AI-assisted",short:"humans led; the AI helped with parts"},{slug:"search-scaffold",label:"Search scaffold",short:"a human-built search harness (FunSearch, AlphaEvolve) with an LLM inside"},{slug:"retrieval",label:"Retrieval",short:"the AI located an existing result rather than producing a new one"}];
const SRC_KINDS = [{slug:"research",label:"Original work",short:"the paper, proof, code or data itself"},{slug:"announcement",label:"Announcement",short:"the claim as first made public, by whoever made it"},{slug:"coverage",label:"Media coverage",short:"news and press reporting on the claim"},{slug:"commentary",label:"Independent commentary",short:"analysis by someone not involved"},{slug:"challenge",label:"Challenge",short:"the case against the claim"}];
const GRADES = {
  "2017-12-14-kepler-90i":["peer-reviewed","search-scaffold"],
  "2020-02-20-halicin":["peer-reviewed","search-scaffold"],
  "2021-04-29-wagner-combinatorics":["independent","search-scaffold"],
  "2021-07-15-alphafold2":["independent","ai-led"],
  "2021-12-01-knot-theory-intuition":["peer-reviewed","ai-assisted"],
  "2022-02-16-tokamak-plasma-control":["peer-reviewed","search-scaffold"],
  "2022-10-05-alphatensor":["peer-reviewed","search-scaffold"],
  "2023-06-07-alphadev":["independent","search-scaffold"],
  "2023-09-19-alphamissense":["peer-reviewed","ai-led"],
  "2023-11-14-graphcast":["peer-reviewed","ai-led"],
  "2023-11-29-a-lab-synthesis":["disputed","ai-led"],
  "2023-11-29-gnome":["disputed","search-scaffold"],
  "2023-12-20-antibiotic-structural-class":["peer-reviewed","search-scaffold"],
  "2023-12-20-coscientist":["peer-reviewed","ai-led"],
  "2023-12-funsearch-binpacking":["peer-reviewed","search-scaffold"],
  "2023-12-funsearch-capset":["peer-reviewed","search-scaffold"],
  "2024-01-17-alphageometry":["peer-reviewed","search-scaffold"],
  "2024-02-21-tearing-mode-avoidance":["peer-reviewed","search-scaffold"],
  "2024-05-08-alphafold3":["peer-reviewed","ai-led"],
  "2024-07-25-alphaproof-imo":["independent","ai-led"],
  "2024-10-02-flywire-connectome":["peer-reviewed","ai-assisted"],
  "2024-11-20-alphaqubit":["peer-reviewed","ai-led"],
  "2025-01-16-esmgfp":["peer-reviewed","ai-led"],
  "2025-01-16-mattergen":["disputed","search-scaffold"],
  "2025-02-13-designed-serine-hydrolases":["peer-reviewed","search-scaffold"],
  "2025-02-ai-coscientist-amr":["peer-reviewed","ai-assisted"],
  "2025-03-12-ai-scientist-workshop-paper":["author-verified","ai-led"],
  "2025-05-alphaevolve-kissing":["independent","search-scaffold"],
  "2025-05-alphaevolve-matmul":["independent","search-scaffold"],
  "2025-05-alphaevolve-minimum-overlap":["independent","search-scaffold"],
  "2025-06-03-rentosertib-phase2a":["peer-reviewed","search-scaffold"],
  "2025-07-21-gemini-deepthink-imo":["independent","ai-led"],
  "2025-07-28-aristotle-imo-lean":["formal","ai-led"],
  "2025-08-gpt5-convex-bound":["known","ai-assisted"],
  "2025-09-11-gauss-strong-pnt":["author-verified","ai-assisted"],
  "2025-09-17-evo-phage-genomes":["peer-reviewed","ai-led"],
  "2025-09-17-unstable-singularities":["author-verified","search-scaffold"],
  "2025-09-25-qma-amplification-limits":["author-verified","ai-assisted"],
  "2025-10-19-gpt5-erdos-retrieval":["known","retrieval"],
  "2025-11-03-alphaevolve-at-scale":["independent","search-scaffold"],
  "2025-11-gpt5-science-acceleration":["peer-reviewed","ai-assisted"],
  "2025-robin-macular":["peer-reviewed","ai-led"],
  "2026-01-alphaevolve-bruhat":["independent","search-scaffold"],
  "2026-01-erdos-728":["formal","autonomous"],
  "2026-05-18-pevac-ps-sarbecovirus":["peer-reviewed","ai-assisted"],
  "2026-05-21-alphaproof-nexus":["formal","search-scaffold"],
  "2026-05-erdos-unit-distance":["independent","ai-led"],
  "2026-06-02-jamming-exponent-identity":["peer-reviewed","collaborative"],
  "2026-06-17-kagome-superconductors":["peer-reviewed","search-scaffold"],
  "2026-06-25-herculaneum-scroll-read":["author-verified","ai-assisted"],
  "2026-07-10-cycle-double-cover":["formal","ai-led"],
  "2026-07-11-grothendieck-group-schemes":["formal","collaborative"],
  "2026-07-14-sabidussi-compatibility":["formal","collaborative"],
  "2026-07-14-zeroth-order-oracle-bound":["formal","ai-led"],
  "2026-07-19-jacobian-conjecture":["formal","collaborative"],
  "2026-07-20-gaussian-moments":["author-verified","ai-led"],
  "2026-07-20-gaussian-product-inequality":["formal","ai-led"],
  "2026-07-20-kourovka-notebook":["formal","autonomous"],
  "2026-07-22-dinitz-garg-goemans":["claimed","ai-led"],
  "2026-07-27-feige-conjecture":["formal","ai-led"],
  "2026-07-28-kemeny-three-voters":["formal","ai-led"],
  "2026-07-29-sumset-difference-exponent":["formal","ai-led"],
  "2026-08-01-astra-ten-advances":["formal","ai-led"],
  "2026-08-04-moore-bound":["formal","ai-assisted"],
  "2026-08-05-schiffer-conjecture":["formal","ai-assisted"],
  "2026-08-05-sendov-conjecture":["formal","collaborative"],
  "2026-08-08-petersen-coloring":["formal","ai-assisted"],
  "2026-08-10-zeta-zeros-critical-line":["formal","ai-led"],
  "2026-08-12-liquid-drop-minimizers":["author-verified","ai-led"],
  "2026-08-13-sop2-sop3":["author-verified","collaborative"]
};
const ID_BY_TITLE = {
  "an eighth planet around kepler-90 found by a neural network":"2017-12-14-kepler-90i",
  "halicin, an antibiotic found by a neural network screening a compound library":"2020-02-20-halicin",
  "reinforcement learning refutes several conjectures in extremal combinatorics":"2021-04-29-wagner-combinatorics",
  "accurate protein structure prediction across the known proteome (alphafold2)":"2021-07-15-alphafold2",
  "two theorems found by machine pattern-spotting in knot theory and representation theory":"2021-12-01-knot-theory-intuition",
  "deep reinforcement learning controls tokamak fusion plasma":"2022-02-16-tokamak-plasma-control",
  "faster matrix-multiplication algorithms found by reinforcement learning":"2022-10-05-alphatensor",
  "faster sorting routines discovered and merged into the llvm c++ library":"2023-06-07-alphadev",
  "pathogenicity predictions for 71 million human missense variants":"2023-09-19-alphamissense",
  "medium-range weather forecasts from a graph neural network beat the operational physics model":"2023-11-14-graphcast",
  "autonomous laboratory reports solid-state synthesis of new inorganic compounds":"2023-11-29-a-lab-synthesis",
  "large-scale prediction of new stable crystalline materials (gnome)":"2023-11-29-gnome",
  "a new structural class of antibiotic candidates against mrsa":"2023-12-20-antibiotic-structural-class",
  "a language-model agent that planned and ran chemistry experiments on lab robots":"2023-12-20-coscientist",
  "improved heuristics for online bin packing":"2023-12-funsearch-binpacking",
  "new lower bound constructions for the cap set problem":"2023-12-funsearch-capset",
  "olympiad geometry solved without human demonstrations":"2024-01-17-alphageometry",
  "reinforcement learning steers a tokamak away from tearing instabilities":"2024-02-21-tearing-mode-avoidance",
  "joint structure prediction for proteins, nucleic acids and ligands (alphafold 3)":"2024-05-08-alphafold3",
  "silver-medal standard at the 2024 international mathematical olympiad":"2024-07-25-alphaproof-imo",
  "complete wiring diagram of an adult fruit-fly brain":"2024-10-02-flywire-connectome",
  "a neural decoder that identifies quantum errors more accurately than hand-designed methods":"2024-11-20-alphaqubit",
  "a working fluorescent protein generated by a language model":"2025-01-16-esmgfp",
  "generative model designs crystals to order; its flagship synthesis turned out to be a known compound":"2025-01-16-mattergen",
  "enzymes with working catalytic machinery designed from scratch":"2025-02-13-designed-serine-hydrolases",
  "ai co-scientist hypotheses on antimicrobial resistance and liver fibrosis":"2025-02-ai-coscientist-amr",
  "a fully machine-generated paper passed workshop peer review":"2025-03-12-ai-scientist-workshop-paper",
  "improved lower bound for the 11-dimensional kissing number":"2025-05-alphaevolve-kissing",
  "4\u00d74 complex matrix multiplication in 48 scalar multiplications":"2025-05-alphaevolve-matmul",
  "improved bound for the erd\u0151s minimum-overlap problem":"2025-05-alphaevolve-minimum-overlap",
  "phase 2a results for a drug whose target and molecule both came from ai":"2025-06-03-rentosertib-phase2a",
  "gold-medal standard at the 2025 international mathematical olympiad":"2025-07-21-gemini-deepthink-imo",
  "machine-checked lean proofs for five of six 2025 imo problems":"2025-07-28-aristotle-imo-lean",
  "improved step-size bound in smooth convex optimization":"2025-08-gpt5-convex-bound",
  "strong prime number theorem formalized in lean by an autoformalization agent":"2025-09-11-gauss-strong-pnt",
  "ai-generated bacteriophage genomes that replicate and kill bacteria":"2025-09-17-evo-phage-genomes",
  "new families of unstable singularities in fluid equations":"2025-09-17-unstable-singularities",
  "limits to black-box amplification in qma, with the key step written by gpt-5":"2025-09-25-qma-amplification-limits",
  "gpt-5 \"solved 10 erd\u0151s problems\": it located existing solutions":"2025-10-19-gpt5-erdos-retrieval",
  "alphaevolve across 67 problems: 20 improvements, 8 regressions":"2025-11-03-alphaevolve-at-scale",
  "early science acceleration experiments with gpt-5":"2025-11-gpt5-science-acceleration",
  "candidate treatment for dry age-related macular degeneration":"2025-robin-macular",
  "structure in bruhat intervals of permutation groups":"2026-01-alphaevolve-bruhat",
  "erd\u0151s problem #728 resolved and formalized in lean":"2026-01-erdos-728",
  "phase 1 trial of a computationally designed pan-sarbecovirus vaccine":"2026-05-18-pevac-ps-sarbecovirus",
  "nine erd\u0151s problems and 44 oeis conjectures proved with machine-checked proofs":"2026-05-21-alphaproof-nexus",
  "disproof of the erd\u0151s unit-distance conjecture":"2026-05-erdos-unit-distance",
  "identity for the critical exponents of jamming derived analytically":"2026-06-02-jamming-exponent-identity",
  "two kagome superconductors predicted by machine learning and confirmed in the lab":"2026-06-17-kagome-superconductors",
  "first herculaneum scroll read end to end without unrolling it":"2026-06-25-herculaneum-scroll-read",
  "cycle double cover conjecture proved for all bridgeless multigraphs":"2026-07-10-cycle-double-cover",
  "counterexample to grothendieck's question on finite flat group schemes":"2026-07-11-grothendieck-group-schemes",
  "sabidussi's compatibility conjecture proved":"2026-07-14-sabidussi-compatibility",
  "near-quadratic lower bound for derivative-free convex optimization":"2026-07-14-zeroth-order-oracle-bound",
  "counterexample to the jacobian conjecture in dimension three":"2026-07-19-jacobian-conjecture",
  "counterexamples to the gaussian moments conjecture":"2026-07-20-gaussian-moments",
  "gaussian product inequality conjecture proved":"2026-07-20-gaussian-product-inequality",
  "eight problems from the kourovka notebook solved and formalized in lean":"2026-07-20-kourovka-notebook",
  "counterexample to the dinitz\u2013garg\u2013goemans conjecture":"2026-07-22-dinitz-garg-goemans",
  "feige's conjecture on sums of nonnegative random variables settled":"2026-07-27-feige-conjecture",
  "kemeny rank aggregation shown np-hard for three voters":"2026-07-28-kemeny-three-voters",
  "optimal exponent relating sumsets and difference sets determined":"2026-07-29-sumset-difference-exponent",
  "ten results in mathematics and theoretical computer science with lean certificates":"2026-08-01-astra-ten-advances",
  "asymptotic degree-diameter problem resolved for fixed diameter":"2026-08-04-moore-bound",
  "counterexamples to schiffer's conjecture and the pompeiu problem":"2026-08-05-schiffer-conjecture",
  "sendov's conjecture proved for every degree":"2026-08-05-sendov-conjecture",
  "a 112-vertex counterexample to the petersen coloring conjecture":"2026-08-08-petersen-coloring",
  "proportion of zeta zeros on the critical line raised to 67.25%":"2026-08-10-zeta-zeros-critical-line",
  "complete minimizer picture for gamow's liquid drop model":"2026-08-12-liquid-drop-minimizers",
  "sop_2 and sop_3 theories shown to coincide":"2026-08-13-sop2-sop3"
};
const TITLE_BY_ID = {
  "2017-12-14-kepler-90i":"An eighth planet around Kepler-90 found by a neural network",
  "2020-02-20-halicin":"Halicin, an antibiotic found by a neural network screening a compound library",
  "2021-04-29-wagner-combinatorics":"Reinforcement learning refutes several conjectures in extremal combinatorics",
  "2021-07-15-alphafold2":"Accurate protein structure prediction across the known proteome (AlphaFold2)",
  "2021-12-01-knot-theory-intuition":"Two theorems found by machine pattern-spotting in knot theory and representation theory",
  "2022-02-16-tokamak-plasma-control":"Deep reinforcement learning controls tokamak fusion plasma",
  "2022-10-05-alphatensor":"Faster matrix-multiplication algorithms found by reinforcement learning",
  "2023-06-07-alphadev":"Faster sorting routines discovered and merged into the LLVM C++ library",
  "2023-09-19-alphamissense":"Pathogenicity predictions for 71 million human missense variants",
  "2023-11-14-graphcast":"Medium-range weather forecasts from a graph neural network beat the operational physics model",
  "2023-11-29-a-lab-synthesis":"Autonomous laboratory reports solid-state synthesis of new inorganic compounds",
  "2023-11-29-gnome":"Large-scale prediction of new stable crystalline materials (GNoME)",
  "2023-12-20-antibiotic-structural-class":"A new structural class of antibiotic candidates against MRSA",
  "2023-12-20-coscientist":"A language-model agent that planned and ran chemistry experiments on lab robots",
  "2023-12-funsearch-binpacking":"Improved heuristics for online bin packing",
  "2023-12-funsearch-capset":"New lower bound constructions for the cap set problem",
  "2024-01-17-alphageometry":"Olympiad geometry solved without human demonstrations",
  "2024-02-21-tearing-mode-avoidance":"Reinforcement learning steers a tokamak away from tearing instabilities",
  "2024-05-08-alphafold3":"Joint structure prediction for proteins, nucleic acids and ligands (AlphaFold 3)",
  "2024-07-25-alphaproof-imo":"Silver-medal standard at the 2024 International Mathematical Olympiad",
  "2024-10-02-flywire-connectome":"Complete wiring diagram of an adult fruit-fly brain",
  "2024-11-20-alphaqubit":"A neural decoder that identifies quantum errors more accurately than hand-designed methods",
  "2025-01-16-esmgfp":"A working fluorescent protein generated by a language model",
  "2025-01-16-mattergen":"Generative model designs crystals to order; its flagship synthesis turned out to be a known compound",
  "2025-02-13-designed-serine-hydrolases":"Enzymes with working catalytic machinery designed from scratch",
  "2025-02-ai-coscientist-amr":"AI co-scientist hypotheses on antimicrobial resistance and liver fibrosis",
  "2025-03-12-ai-scientist-workshop-paper":"A fully machine-generated paper passed workshop peer review",
  "2025-05-alphaevolve-kissing":"Improved lower bound for the 11-dimensional kissing number",
  "2025-05-alphaevolve-matmul":"4\u00d74 complex matrix multiplication in 48 scalar multiplications",
  "2025-05-alphaevolve-minimum-overlap":"Improved bound for the Erd\u0151s minimum-overlap problem",
  "2025-06-03-rentosertib-phase2a":"Phase 2a results for a drug whose target and molecule both came from AI",
  "2025-07-21-gemini-deepthink-imo":"Gold-medal standard at the 2025 International Mathematical Olympiad",
  "2025-07-28-aristotle-imo-lean":"Machine-checked Lean proofs for five of six 2025 IMO problems",
  "2025-08-gpt5-convex-bound":"Improved step-size bound in smooth convex optimization",
  "2025-09-11-gauss-strong-pnt":"Strong prime number theorem formalized in Lean by an autoformalization agent",
  "2025-09-17-evo-phage-genomes":"AI-generated bacteriophage genomes that replicate and kill bacteria",
  "2025-09-17-unstable-singularities":"New families of unstable singularities in fluid equations",
  "2025-09-25-qma-amplification-limits":"Limits to black-box amplification in QMA, with the key step written by GPT-5",
  "2025-10-19-gpt5-erdos-retrieval":"GPT-5 \"solved 10 Erd\u0151s problems\": it located existing solutions",
  "2025-11-03-alphaevolve-at-scale":"AlphaEvolve across 67 problems: 20 improvements, 8 regressions",
  "2025-11-gpt5-science-acceleration":"Early science acceleration experiments with GPT-5",
  "2025-robin-macular":"Candidate treatment for dry age-related macular degeneration",
  "2026-01-alphaevolve-bruhat":"Structure in Bruhat intervals of permutation groups",
  "2026-01-erdos-728":"Erd\u0151s problem #728 resolved and formalized in Lean",
  "2026-05-18-pevac-ps-sarbecovirus":"Phase 1 trial of a computationally designed pan-sarbecovirus vaccine",
  "2026-05-21-alphaproof-nexus":"Nine Erd\u0151s problems and 44 OEIS conjectures proved with machine-checked proofs",
  "2026-05-erdos-unit-distance":"Disproof of the Erd\u0151s unit-distance conjecture",
  "2026-06-02-jamming-exponent-identity":"Identity for the critical exponents of jamming derived analytically",
  "2026-06-17-kagome-superconductors":"Two kagome superconductors predicted by machine learning and confirmed in the lab",
  "2026-06-25-herculaneum-scroll-read":"First Herculaneum scroll read end to end without unrolling it",
  "2026-07-10-cycle-double-cover":"Cycle double cover conjecture proved for all bridgeless multigraphs",
  "2026-07-11-grothendieck-group-schemes":"Counterexample to Grothendieck's question on finite flat group schemes",
  "2026-07-14-sabidussi-compatibility":"Sabidussi's compatibility conjecture proved",
  "2026-07-14-zeroth-order-oracle-bound":"Near-quadratic lower bound for derivative-free convex optimization",
  "2026-07-19-jacobian-conjecture":"Counterexample to the Jacobian conjecture in dimension three",
  "2026-07-20-gaussian-moments":"Counterexamples to the Gaussian moments conjecture",
  "2026-07-20-gaussian-product-inequality":"Gaussian product inequality conjecture proved",
  "2026-07-20-kourovka-notebook":"Eight problems from the Kourovka Notebook solved and formalized in Lean",
  "2026-07-22-dinitz-garg-goemans":"Counterexample to the Dinitz\u2013Garg\u2013Goemans conjecture",
  "2026-07-27-feige-conjecture":"Feige's conjecture on sums of nonnegative random variables settled",
  "2026-07-28-kemeny-three-voters":"Kemeny rank aggregation shown NP-hard for three voters",
  "2026-07-29-sumset-difference-exponent":"Optimal exponent relating sumsets and difference sets determined",
  "2026-08-01-astra-ten-advances":"Ten results in mathematics and theoretical computer science with Lean certificates",
  "2026-08-04-moore-bound":"Asymptotic degree-diameter problem resolved for fixed diameter",
  "2026-08-05-schiffer-conjecture":"Counterexamples to Schiffer's conjecture and the Pompeiu problem",
  "2026-08-05-sendov-conjecture":"Sendov's conjecture proved for every degree",
  "2026-08-08-petersen-coloring":"A 112-vertex counterexample to the Petersen coloring conjecture",
  "2026-08-10-zeta-zeros-critical-line":"Proportion of zeta zeros on the critical line raised to 67.25%",
  "2026-08-12-liquid-drop-minimizers":"Complete minimizer picture for Gamow's liquid drop model",
  "2026-08-13-sop2-sop3":"SOP_2 and SOP_3 theories shown to coincide"
};
/*VOCAB:END*/

  const $ = sel => document.querySelector(sel);
  const $$ = sel => [...document.querySelectorAll(sel)];
  const esc = window.wafEsc;

  const show = window.wafShow;

  const form = $('[data-form]');
  if (!form) return;

  let kind = 'check';
  let step = 1;

  // ---------- errors ----------
  const clearErrors = () => $$('[data-err]').forEach(el => { el.hidden = true; el.textContent = ''; });
  function setError(field, message) {
    // The server names its errors after payload fields (who_missing, citation_invalid).
    // Strip the suffix so one message finds the right slot without a lookup table that
    // would need updating every time a rule is added.
    const key = String(field).replace(/_(missing|invalid|too_long|too_many|em_dash|markup|unchanged|taken)$/, '');
    const el = document.querySelector(`[data-err="${CSS.escape(key)}"]`) || $('[data-err="_"]');
    if (!el) return;
    el.textContent = message;
    el.hidden = false;
    el.scrollIntoView({ block: 'center', behavior: 'smooth' });
  }

  // ---------- which kind ----------
  function selectKind(next) {
    kind = next;
    $$('[data-kinds] .c-kind').forEach(b => {
      b.setAttribute('aria-pressed', b.dataset.kind === next ? 'true' : 'false');
    });
    $$('.c-fields').forEach(f => { f.hidden = f.dataset.for !== next; });
    // A new entry does not refer to an existing one.
    $('[data-entrypick]').hidden = next === 'entry';
    // The wizard owns its own navigation; the other three submit in one go.
    $('[data-actions]').hidden = next === 'entry' && step < 4;
    if (next === 'entry') goStep(1);
    if (next === 'challenge') syncChallenge();
    clearErrors();
  }

  $('[data-kinds]').addEventListener('click', ev => {
    const b = ev.target.closest('.c-kind');
    if (b) selectKind(b.dataset.kind);
  });

  // ---------- the entry picker ----------
  // A datalist gives the browser's own autocomplete over 52 titles with no script, and
  // the input's value ends up as the id because that is what each option carries.
  const entryInput = $('#c-entry');

  // The picker holds titles, because that is what a datalist filters on and what a
  // contributor knows. This resolves whatever is in the box to an id: a title picked
  // from the list, a title typed in any capitalisation, or an id pasted from a URL.
  function currentEntry() {
    const v = entryInput.value.trim();
    if (Object.hasOwn(GRADES, v)) return v;
    const byTitle = ID_BY_TITLE[v.toLowerCase()];
    return Object.hasOwn(ID_BY_TITLE, v.toLowerCase()) ? byTitle : '';
  }

  function syncChallenge() {
    const id = currentEntry();
    const now = Object.hasOwn(GRADES, id) ? GRADES[id] : null;
    const box = $('[data-current]');
    box.hidden = !now;
    if (now) {
      const ver = VER.find(v => v.slug === now[0]);
      const aut = AUT.find(a => a.slug === now[1]);
      $('[data-current-pills]').innerHTML =
        `<span class="pill v v-${esc(now[0])}">${esc(ver ? ver.label : now[0])}</span>`
        + `<span class="pill a a-${esc(now[1])}">${esc(aut ? aut.label : now[1])}</span>`;
    }
    // The proposed-grade select follows the axis, minus the grade already set: nothing
    // is gained by offering the answer the server will refuse.
    const axis = $('#f-axis').value;
    const list = axis === 'verification' ? VER : AUT;
    const set = now ? (axis === 'verification' ? now[0] : now[1]) : null;
    const sel = $('[data-proposed]');
    sel.innerHTML = list.filter(g => g.slug !== set)
      .map(g => `<option value="${esc(g.slug)}" title="${esc(g.short)}">${esc(g.label)}</option>`)
      .join('');
    gradeHelp();
  }

  function gradeHelp() {
    const axis = $('#f-axis').value;
    const list = axis === 'verification' ? VER : AUT;
    const g = list.find(x => x.slug === $('[data-proposed]').value);
    $('[data-grade-help]').textContent = g ? g.short : '';
  }

  entryInput.addEventListener('change', () => { if (kind === 'challenge') syncChallenge(); });
  entryInput.addEventListener('input', () => { if (kind === 'challenge') syncChallenge(); });
  $('#f-axis').addEventListener('change', syncChallenge);
  $('[data-proposed]').addEventListener('change', gradeHelp);

  // ---------- correction: show only the fields the target needs ----------
  function syncCorrection() {
    const target = $('#f-target').value;
    $$('[data-when]').forEach(el => {
      el.hidden = !el.dataset.when.split(' ').includes(target);
    });
  }
  $('#f-target').addEventListener('change', syncCorrection);

  const srcHelp = () => {
    const k = SRC_KINDS.find(s => s.slug === $('#f-sourceKind').value);
    $('[data-sourcekind-help]').textContent = k ? k.short : '';
  };
  $('#f-sourceKind').addEventListener('change', srcHelp);

  // ---------- the new-entry wizard ----------
  function goStep(n) {
    step = n;
    $$('[data-stepbody]').forEach(el => { el.hidden = Number(el.dataset.stepbody) !== n; });
    $$('[data-steps] li').forEach(li => {
      const i = Number(li.dataset.step);
      li.classList.toggle('done', i < n);
      if (i === n) li.setAttribute('aria-current', 'step');
      else li.removeAttribute('aria-current');
    });
    $('[data-back]').hidden = n === 1;
    $('[data-next]').hidden = n === 4;
    $('[data-actions]').hidden = n !== 4;
    if (n === 3) checkRule4();
  }
  $('[data-next]').addEventListener('click', () => goStep(Math.min(step + 1, 4)));
  $('[data-back]').addEventListener('click', () => goStep(Math.max(step - 1, 1)));

  // ---------- sources ----------
  const sourceOptions = SRC_KINDS
    .map(s => `<option value="${esc(s.slug)}" title="${esc(s.short)}">${esc(s.label)}</option>`)
    .join('');

  function addSource(values = {}) {
    const wrap = document.createElement('div');
    wrap.className = 'c-source';
    wrap.innerHTML =
      `<div class="fld"><label>Link</label>`
      + `<input type="url" data-s="url" maxlength="500" placeholder="https://" value="${esc(values.url || '')}"></div>`
      + `<div class="fld"><label>What to call it</label>`
      + `<input type="text" data-s="label" maxlength="160" value="${esc(values.label || '')}"></div>`
      + `<div class="fld"><label>Kind</label><select data-s="kind">${sourceOptions}</select></div>`
      + `<button type="button" class="c-drop" data-drop aria-label="Remove this source">Remove</button>`;
    $('[data-sources]').appendChild(wrap);
    if (values.kind) wrap.querySelector('[data-s=kind]').value = values.kind;
    wrap.addEventListener('input', checkRule4);
    wrap.addEventListener('change', checkRule4);
    checkRule4();
  }

  $('[data-addsource]').addEventListener('click', () => addSource());
  $('[data-sources]').addEventListener('click', ev => {
    if (!ev.target.closest('[data-drop]')) return;
    // Never leave zero: the form's own rule is at least one source, and an empty list
    // is a state the submitter has to dig out of.
    if ($$('[data-sources] .c-source').length <= 1) return;
    ev.target.closest('.c-source').remove();
    checkRule4();
  });

  function readSources() {
    return $$('[data-sources] .c-source').map(row => ({
      url: row.querySelector('[data-s=url]').value.trim(),
      label: row.querySelector('[data-s=label]').value.trim(),
      kind: row.querySelector('[data-s=kind]').value,
    })).filter(s => s.url || s.label);
  }

  // Editorial rule 4, stated before it is enforced. The build refuses a grade above
  // "claimed" with no research source, and finding that out from a rejected submission
  // teaches the rule far more expensively than a line of text does.
  function checkRule4() {
    const note = $('[data-rule4]');
    if (!note) return;
    const grade = $('#f-verification').value;
    const hasResearch = readSources().some(s => s.kind === 'research');
    if (grade && grade !== 'claimed' && !hasResearch) {
      const label = (VER.find(v => v.slug === grade) || {}).label || grade;
      note.textContent = `A grade of "${label}" needs a research source: a paper, a preprint, `
        + 'a proof or a repository. With only an announcement, the grade is "claimed".';
      note.hidden = false;
    } else {
      note.hidden = true;
    }
  }
  // Declared before they are wired up: passing a `const` arrow to addEventListener
  // reads it immediately, and doing that above its declaration throws on load rather
  // than when the control is used.
  function verHelp() {
    const g = VER.find(v => v.slug === $('#f-verification').value);
    $('[data-ver-help]').textContent = g ? g.short : '';
  }
  function autHelp() {
    const g = AUT.find(a => a.slug === $('#f-autonomy').value);
    $('[data-aut-help]').textContent = g ? g.short : '';
  }

  $('#f-verification').addEventListener('change', () => { verHelp(); checkRule4(); });
  $('#f-autonomy').addEventListener('change', autHelp);

  // ---------- suggest an id ----------
  // YYYY-MM-DD-short-name, the convention every existing id follows. Suggested rather
  // than imposed: it is permanent once merged, so the field stays editable.
  function suggestId() {
    const idField = $('#f-id');
    if (idField.dataset.touched === '1') return;
    const date = $('#f-date').value || '';
    const slug = $('#f-title').value.toLowerCase()
      .normalize('NFD').replace(/[\u0300-\u036f]/g, '')
      .replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')
      .split('-').slice(0, 4).join('-');
    idField.value = [date, slug].filter(Boolean).join('-').slice(0, 80);
  }
  $('#f-title').addEventListener('input', suggestId);
  $('#f-date').addEventListener('change', suggestId);
  $('#f-id').addEventListener('input', ev => { ev.target.dataset.touched = '1'; });

  // ---------- build the payload ----------
  const val = id => $(id).value.trim();
  const listOf = id => val(id).split(',').map(s => s.trim()).filter(Boolean);

  function payloadFor(k) {
    if (k === 'check') {
      return { who: val('#f-who'), outcome: val('#f-outcome'), evidence: val('#f-evidence'),
               url: val('#f-checkurl'), coi: val('#f-coi') };
    }
    if (k === 'challenge') {
      return { axis: $('#f-axis').value, proposed: $('[data-proposed]').value,
               citation: val('#f-citation'), citationLabel: val('#f-citationLabel'),
               why: val('#f-why'), coi: val('#f-challengeCoi') };
    }
    if (k === 'correction') {
      const target = $('#f-target').value;
      const p = { target, note: val('#f-note') };
      if (target === 'year_posed') p.year = Number(val('#f-year'));
      else {
        p.url = val('#f-corrurl');
        p.label = val('#f-label');
        if (target === 'source') p.sourceKind = $('#f-sourceKind').value;
      }
      return p;
    }
    const p = {
      id: val('#f-id'), title: val('#f-title'), claim: val('#f-claim'),
      field: $('#f-field').value, date: val('#f-date'), added: val('#f-date'),
      lab: val('#f-lab') || 'Independent', model: val('#f-model') || 'Unknown',
      verification: $('#f-verification').value, autonomy: $('#f-autonomy').value,
      sources: readSources(),
      novelty_check: val('#f-novelty'),
    };
    if (val('#f-detail')) p.detail = val('#f-detail');
    if (val('#f-caveats')) p.caveats = val('#f-caveats');
    if (val('#f-yearposed')) p.year_posed = Number(val('#f-yearposed'));
    if (listOf('#f-humans').length) p.humans = listOf('#f-humans');
    if (listOf('#f-tags').length) p.tags = listOf('#f-tags').map(t => t.toLowerCase());
    return p;
  }

  const DONE = {
    check: 'Your check is in the queue. A maintainer reads it, and if it holds up it is '
      + 'added to the entry with you credited as a reviewer.',
    challenge: 'Your challenge is in the queue. If it holds up, the grade moves and the '
      + 'change is recorded on the entry with your citation beside it.',
    correction: 'Your correction is in the queue. Corrections are recorded on the entry '
      + 'rather than applied silently.',
    entry: 'Your entry is in the queue. A maintainer checks the sources and the novelty '
      + 'claim before it joins the registry.',
  };

  // ---------- submit ----------
  form.addEventListener('submit', async ev => {
    ev.preventDefault();
    clearErrors();

    const entryId = kind === 'entry' ? null : currentEntry();
    if (kind !== 'entry' && !entryId) {
      setError('entry', 'Pick an entry from the list.');
      return;
    }

    const btn = $('[data-submit]');
    btn.disabled = true;
    try {
      const r = await fetch('/api/proposals', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ kind, entryId, payload: payloadFor(kind) }),
      });
      const out = await r.json().catch(() => ({}));
      if (!r.ok) {
        if (r.status === 401) {
          show('out');
          return;
        }
        setError(out.error || '_', out.message || 'That could not be submitted.');
        return;
      }
      $('[data-done-msg]').textContent = DONE[kind] || DONE.check;
      form.hidden = true;
      $('[data-entrypick]').hidden = true;
      $('[data-kinds]').hidden = true;
      $('[data-done]').hidden = false;
    } catch {
      setError('_', 'Could not reach the server. Check your connection and try again.');
    } finally {
      btn.disabled = false;
    }
  });

  $('[data-again]').addEventListener('click', () => {
    form.reset();
    $('[data-done]').hidden = true;
    form.hidden = false;
    $('[data-kinds]').hidden = false;
    $('[data-sources]').innerHTML = '';
    addSource();
    $('#f-id').dataset.touched = '';
    selectKind(kind);
  });

  // ---------- boot ----------
  // A finding page links straight here with the kind and the entry filled in, so the
  // reader who clicked "Submit a check" on an entry does not have to find it again.
  function fromQuery() {
    const q = new URLSearchParams(location.search);
    const k = q.get('kind');
    const e = q.get('entry');
    // The link carries an id; the box holds a title. Show the title, so what the
    // reader sees matches the entry they just came from.
    if (e && Object.hasOwn(TITLE_BY_ID, e)) entryInput.value = TITLE_BY_ID[e];
    if (k && ['check', 'challenge', 'correction', 'entry'].includes(k)) selectKind(k);
    else selectKind('check');
  }

  const session = window.wafSession || Promise.resolve({ signedIn: false });
  session.then(data => {
    if (!data.signedIn) {
      const btn = $('[data-signin-btn]');
      if (btn) {
        btn.href = '/api/auth/start?return_to='
          + encodeURIComponent(location.pathname + location.search);
      }
      show('out');
      return;
    }
    // Seed the check form with what we already know, so the commonest contribution is
    // one field away from done.
    if (data.account) {
      $('#f-who').value = data.account.displayName || data.account.handle || '';
    }
    addSource();
    verHelp();
    autHelp();
    srcHelp();
    syncCorrection();
    fromQuery();
    show('in');
  }).catch(() => show('out'));
})();
