// What the registry currently contains, as data the API can check against.
//
// Everything between the markers is generated by scripts/build-site.py from
// data/entries.json and data/vocab.json. Do not edit it by hand: `python3
// scripts/build.py` rewrites it, and CI rebuilds and fails on any difference.
//
// Why generate it rather than read the JSON at runtime. A Vercel function that opens
// data/entries.json depends on that file being traced into the bundle, which is a
// deployment detail that fails quietly and only in production. A generated module is
// imported like any other, is visible in review as a diff, and cannot disagree with the
// vocabulary the build enforces, because the same run writes both.
//
// This is the same device build-site.py already uses for app.js, which cannot read
// data/vocab.json in a browser either. One source, two generated copies, both checked.

/*REGISTRY:START*/
export const ENTRY_IDS = new Set([
  "2017-12-14-kepler-90i",
  "2020-02-20-halicin",
  "2021-04-29-wagner-combinatorics",
  "2021-07-15-alphafold2",
  "2021-12-01-knot-theory-intuition",
  "2022-02-16-tokamak-plasma-control",
  "2022-10-05-alphatensor",
  "2023-06-07-alphadev",
  "2023-09-19-alphamissense",
  "2023-11-14-graphcast",
  "2023-11-29-a-lab-synthesis",
  "2023-11-29-gnome",
  "2023-12-20-antibiotic-structural-class",
  "2023-12-20-coscientist",
  "2023-12-funsearch-binpacking",
  "2023-12-funsearch-capset",
  "2024-01-17-alphageometry",
  "2024-02-21-tearing-mode-avoidance",
  "2024-05-08-alphafold3",
  "2024-07-25-alphaproof-imo",
  "2024-10-02-flywire-connectome",
  "2024-11-20-alphaqubit",
  "2025-01-16-esmgfp",
  "2025-01-16-mattergen",
  "2025-02-13-designed-serine-hydrolases",
  "2025-02-ai-coscientist-amr",
  "2025-03-12-ai-scientist-workshop-paper",
  "2025-05-alphaevolve-kissing",
  "2025-05-alphaevolve-matmul",
  "2025-05-alphaevolve-minimum-overlap",
  "2025-06-03-rentosertib-phase2a",
  "2025-07-21-gemini-deepthink-imo",
  "2025-07-28-aristotle-imo-lean",
  "2025-08-gpt5-convex-bound",
  "2025-09-11-gauss-strong-pnt",
  "2025-09-17-evo-phage-genomes",
  "2025-09-17-unstable-singularities",
  "2025-09-25-qma-amplification-limits",
  "2025-10-19-gpt5-erdos-retrieval",
  "2025-11-03-alphaevolve-at-scale",
  "2025-11-gpt5-science-acceleration",
  "2025-robin-macular",
  "2026-01-alphaevolve-bruhat",
  "2026-01-erdos-728",
  "2026-05-21-alphaproof-nexus",
  "2026-05-erdos-unit-distance",
  "2026-06-25-herculaneum-scroll-read",
  "2026-07-11-grothendieck-group-schemes",
  "2026-07-14-zeroth-order-oracle-bound",
  "2026-07-19-jacobian-conjecture",
  "2026-07-20-gaussian-moments",
  "2026-07-22-dinitz-garg-goemans"
]);
export const ENTRY_GRADES = {
  "2017-12-14-kepler-90i": ["peer-reviewed", "search-scaffold"],
  "2020-02-20-halicin": ["peer-reviewed", "search-scaffold"],
  "2021-04-29-wagner-combinatorics": ["independent", "search-scaffold"],
  "2021-07-15-alphafold2": ["independent", "ai-led"],
  "2021-12-01-knot-theory-intuition": ["peer-reviewed", "ai-assisted"],
  "2022-02-16-tokamak-plasma-control": ["peer-reviewed", "search-scaffold"],
  "2022-10-05-alphatensor": ["peer-reviewed", "search-scaffold"],
  "2023-06-07-alphadev": ["independent", "search-scaffold"],
  "2023-09-19-alphamissense": ["peer-reviewed", "ai-led"],
  "2023-11-14-graphcast": ["peer-reviewed", "ai-led"],
  "2023-11-29-a-lab-synthesis": ["disputed", "ai-led"],
  "2023-11-29-gnome": ["disputed", "search-scaffold"],
  "2023-12-20-antibiotic-structural-class": ["peer-reviewed", "search-scaffold"],
  "2023-12-20-coscientist": ["peer-reviewed", "ai-led"],
  "2023-12-funsearch-binpacking": ["peer-reviewed", "search-scaffold"],
  "2023-12-funsearch-capset": ["peer-reviewed", "search-scaffold"],
  "2024-01-17-alphageometry": ["peer-reviewed", "search-scaffold"],
  "2024-02-21-tearing-mode-avoidance": ["peer-reviewed", "search-scaffold"],
  "2024-05-08-alphafold3": ["peer-reviewed", "ai-led"],
  "2024-07-25-alphaproof-imo": ["independent", "ai-led"],
  "2024-10-02-flywire-connectome": ["peer-reviewed", "ai-assisted"],
  "2024-11-20-alphaqubit": ["peer-reviewed", "ai-led"],
  "2025-01-16-esmgfp": ["peer-reviewed", "ai-led"],
  "2025-01-16-mattergen": ["disputed", "search-scaffold"],
  "2025-02-13-designed-serine-hydrolases": ["peer-reviewed", "search-scaffold"],
  "2025-02-ai-coscientist-amr": ["author-verified", "ai-assisted"],
  "2025-03-12-ai-scientist-workshop-paper": ["author-verified", "ai-led"],
  "2025-05-alphaevolve-kissing": ["independent", "search-scaffold"],
  "2025-05-alphaevolve-matmul": ["independent", "search-scaffold"],
  "2025-05-alphaevolve-minimum-overlap": ["independent", "search-scaffold"],
  "2025-06-03-rentosertib-phase2a": ["peer-reviewed", "search-scaffold"],
  "2025-07-21-gemini-deepthink-imo": ["independent", "ai-led"],
  "2025-07-28-aristotle-imo-lean": ["formal", "ai-led"],
  "2025-08-gpt5-convex-bound": ["known", "ai-assisted"],
  "2025-09-11-gauss-strong-pnt": ["author-verified", "ai-assisted"],
  "2025-09-17-evo-phage-genomes": ["peer-reviewed", "ai-led"],
  "2025-09-17-unstable-singularities": ["author-verified", "search-scaffold"],
  "2025-09-25-qma-amplification-limits": ["author-verified", "ai-assisted"],
  "2025-10-19-gpt5-erdos-retrieval": ["known", "retrieval"],
  "2025-11-03-alphaevolve-at-scale": ["independent", "search-scaffold"],
  "2025-11-gpt5-science-acceleration": ["peer-reviewed", "ai-assisted"],
  "2025-robin-macular": ["claimed", "ai-led"],
  "2026-01-alphaevolve-bruhat": ["independent", "search-scaffold"],
  "2026-01-erdos-728": ["formal", "autonomous"],
  "2026-05-21-alphaproof-nexus": ["formal", "search-scaffold"],
  "2026-05-erdos-unit-distance": ["independent", "ai-led"],
  "2026-06-25-herculaneum-scroll-read": ["author-verified", "ai-assisted"],
  "2026-07-11-grothendieck-group-schemes": ["formal", "collaborative"],
  "2026-07-14-zeroth-order-oracle-bound": ["formal", "ai-led"],
  "2026-07-19-jacobian-conjecture": ["formal", "collaborative"],
  "2026-07-20-gaussian-moments": ["author-verified", "ai-led"],
  "2026-07-22-dinitz-garg-goemans": ["claimed", "ai-led"]
};
export const ENTRY_TITLES = {
  "2017-12-14-kepler-90i": "An eighth planet around Kepler-90 found by a neural network",
  "2020-02-20-halicin": "Halicin, an antibiotic found by a neural network screening a compound library",
  "2021-04-29-wagner-combinatorics": "Reinforcement learning refutes several conjectures in extremal combinatorics",
  "2021-07-15-alphafold2": "Accurate protein structure prediction across the known proteome (AlphaFold2)",
  "2021-12-01-knot-theory-intuition": "Two theorems found by machine pattern-spotting in knot theory and representation theory",
  "2022-02-16-tokamak-plasma-control": "Deep reinforcement learning controls tokamak fusion plasma",
  "2022-10-05-alphatensor": "Faster matrix-multiplication algorithms found by reinforcement learning",
  "2023-06-07-alphadev": "Faster sorting routines discovered and merged into the LLVM C++ library",
  "2023-09-19-alphamissense": "Pathogenicity predictions for 71 million human missense variants",
  "2023-11-14-graphcast": "Medium-range weather forecasts from a graph neural network beat the operational physics model",
  "2023-11-29-a-lab-synthesis": "Autonomous laboratory reports solid-state synthesis of new inorganic compounds",
  "2023-11-29-gnome": "Large-scale prediction of new stable crystalline materials (GNoME)",
  "2023-12-20-antibiotic-structural-class": "A new structural class of antibiotic candidates against MRSA",
  "2023-12-20-coscientist": "A language-model agent that planned and ran chemistry experiments on lab robots",
  "2023-12-funsearch-binpacking": "Improved heuristics for online bin packing",
  "2023-12-funsearch-capset": "New lower bound constructions for the cap set problem",
  "2024-01-17-alphageometry": "Olympiad geometry solved without human demonstrations",
  "2024-02-21-tearing-mode-avoidance": "Reinforcement learning steers a tokamak away from tearing instabilities",
  "2024-05-08-alphafold3": "Joint structure prediction for proteins, nucleic acids and ligands (AlphaFold 3)",
  "2024-07-25-alphaproof-imo": "Silver-medal standard at the 2024 International Mathematical Olympiad",
  "2024-10-02-flywire-connectome": "Complete wiring diagram of an adult fruit-fly brain",
  "2024-11-20-alphaqubit": "A neural decoder that identifies quantum errors more accurately than hand-designed methods",
  "2025-01-16-esmgfp": "A working fluorescent protein generated by a language model",
  "2025-01-16-mattergen": "Generative model designs crystals to order; its flagship synthesis turned out to be a known compound",
  "2025-02-13-designed-serine-hydrolases": "Enzymes with working catalytic machinery designed from scratch",
  "2025-02-ai-coscientist-amr": "AI co-scientist hypotheses on antimicrobial resistance and liver fibrosis",
  "2025-03-12-ai-scientist-workshop-paper": "A fully machine-generated paper passed workshop peer review",
  "2025-05-alphaevolve-kissing": "Improved lower bound for the 11-dimensional kissing number",
  "2025-05-alphaevolve-matmul": "4\u00d74 complex matrix multiplication in 48 scalar multiplications",
  "2025-05-alphaevolve-minimum-overlap": "Improved bound for the Erd\u0151s minimum-overlap problem",
  "2025-06-03-rentosertib-phase2a": "Phase 2a results for a drug whose target and molecule both came from AI",
  "2025-07-21-gemini-deepthink-imo": "Gold-medal standard at the 2025 International Mathematical Olympiad",
  "2025-07-28-aristotle-imo-lean": "Machine-checked Lean proofs for five of six 2025 IMO problems",
  "2025-08-gpt5-convex-bound": "Improved step-size bound in smooth convex optimization",
  "2025-09-11-gauss-strong-pnt": "Strong prime number theorem formalized in Lean by an autoformalization agent",
  "2025-09-17-evo-phage-genomes": "AI-generated bacteriophage genomes that replicate and kill bacteria",
  "2025-09-17-unstable-singularities": "New families of unstable singularities in fluid equations",
  "2025-09-25-qma-amplification-limits": "Limits to black-box amplification in QMA, with the key step written by GPT-5",
  "2025-10-19-gpt5-erdos-retrieval": "GPT-5 \"solved 10 Erd\u0151s problems\": it located existing solutions",
  "2025-11-03-alphaevolve-at-scale": "AlphaEvolve across 67 problems: 20 improvements, 8 regressions",
  "2025-11-gpt5-science-acceleration": "Early science acceleration experiments with GPT-5",
  "2025-robin-macular": "Candidate treatment for dry age-related macular degeneration",
  "2026-01-alphaevolve-bruhat": "Structure in Bruhat intervals of permutation groups",
  "2026-01-erdos-728": "Erd\u0151s problem #728 resolved and formalized in Lean",
  "2026-05-21-alphaproof-nexus": "Nine Erd\u0151s problems and 44 OEIS conjectures proved with machine-checked proofs",
  "2026-05-erdos-unit-distance": "Disproof of the Erd\u0151s unit-distance conjecture",
  "2026-06-25-herculaneum-scroll-read": "First Herculaneum scroll read end to end without unrolling it",
  "2026-07-11-grothendieck-group-schemes": "Counterexample to Grothendieck's question on finite flat group schemes",
  "2026-07-14-zeroth-order-oracle-bound": "Near-quadratic lower bound for derivative-free convex optimization",
  "2026-07-19-jacobian-conjecture": "Counterexample to the Jacobian conjecture in dimension three",
  "2026-07-20-gaussian-moments": "Counterexamples to the Gaussian moments conjecture",
  "2026-07-22-dinitz-garg-goemans": "Counterexample to the Dinitz\u2013Garg\u2013Goemans conjecture"
};
export const VERIFICATION = ["formal", "independent", "peer-reviewed", "author-verified", "claimed", "disputed", "known", "refuted"];
export const AUTONOMY = ["autonomous", "ai-led", "collaborative", "ai-assisted", "search-scaffold", "retrieval"];
export const SOURCE_KINDS = ["research", "announcement", "coverage", "commentary", "challenge"];
export const FIELDS = ["archaeology", "astronomy", "biology", "chemistry", "climate", "computer-science", "economics", "engineering", "materials", "mathematics", "medicine", "neuroscience", "physics"];
/*REGISTRY:END*/

/** The three triage signals. Kept in step with the CHECK in db/002_signals.sql. */
export const SIGNAL_KINDS = ["needs-check", "looks-wrong", "dead-link"];

/**
 * Is this an entry that actually exists?
 *
 * An allowlist rather than a pattern. A shape check would let a signal or a proposal be
 * filed against an id nobody can navigate to, which is invisible rather than harmless:
 * the row is real, it counts, and no page will ever show it so nobody can dispute it.
 */
export function isEntryId(v) {
  return typeof v === "string" && ENTRY_IDS.has(v);
}

export function isSignalKind(v) {
  return SIGNAL_KINDS.includes(v);
}

/**
 * The grades an entry currently carries, as {verification, autonomy}, or null.
 *
 * Enough to refuse a grade challenge that proposes the grade already set. Deliberately
 * not enough to render anything: the registry is served from data/entries.json and the
 * pre-built HTML, and a second copy of it here would be a second thing to keep in step.
 */
export function entryGrades(id) {
  const g = Object.hasOwn(ENTRY_GRADES, id) ? ENTRY_GRADES[id] : null;
  return g ? { verification: g[0], autonomy: g[1] } : null;
}

/**
 * An entry's title, or null.
 *
 * Object.hasOwn rather than a plain lookup, here and above: a bare `ENTRY_TITLES[id]`
 * with id set to "constructor" or "toString" returns something truthy off the
 * prototype, and this value is rendered.
 */
export function entryTitle(id) {
  return Object.hasOwn(ENTRY_TITLES, id) ? ENTRY_TITLES[id] : null;
}
