// api/_lib/registry.js is generated by scripts/build.py from data/entries.json and
// data/vocab.json. These tests are the thing that notices when it has not been.
//
// The failure mode is quiet and unpleasant: a stale allowlist means a signal or a
// proposal filed against a real, published entry is rejected as "unknown_entry", and
// the only symptom is a reader being told their click did not count. CI rebuilds and
// diffs, which catches a forgotten build; this catches a hand edit that produced a file
// the build would not have produced.
import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import {
  ENTRY_IDS, VERIFICATION, AUTONOMY, SOURCE_KINDS, FIELDS,
  SIGNAL_KINDS, isEntryId, isSignalKind,
} from "./registry.js";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");
const read = p => JSON.parse(fs.readFileSync(path.join(ROOT, p), "utf8"));
const ENTRIES = read("data/entries.json");
const VOCAB = read("data/vocab.json");
const SQL = fs.readFileSync(path.join(ROOT, "db/002_signals.sql"), "utf8");

test("every published entry is in the allowlist", () => {
  for (const e of ENTRIES) {
    assert.ok(isEntryId(e.id), `${e.id} is published but api/_lib/registry.js does not know it. `
      + "Run python3 scripts/build.py");
  }
});

test("the allowlist contains nothing that is not published", () => {
  // The other direction. A stale id here would accept signals for an entry that has
  // been removed, and no page would ever show them.
  const published = new Set(ENTRIES.map(e => e.id));
  for (const id of ENTRY_IDS) {
    assert.ok(published.has(id), `${id} is in registry.js but not in data/entries.json`);
  }
});

test("the generated vocabularies match data/vocab.json", () => {
  assert.deepEqual(VERIFICATION, VOCAB.verification.map(v => v.slug));
  assert.deepEqual(AUTONOMY, VOCAB.autonomy.map(a => a.slug));
  assert.deepEqual(SOURCE_KINDS, VOCAB.source_kinds.map(s => s.slug));
  assert.deepEqual(FIELDS, Object.keys(VOCAB.fields).sort());
});

test("the signal kinds match data/vocab.json and the CHECK constraint", () => {
  // Three copies of one list: vocab.json drives the buttons, registry.js validates the
  // POST, and the CHECK constraint is the last word. A slug in the first two but not
  // the third renders a button whose every click is rejected by Postgres.
  assert.deepEqual([...SIGNAL_KINDS].sort(), VOCAB.signal_kinds.map(s => s.slug).sort());

  const m = SQL.match(/check \(kind in \(([^)]+)\)\)/);
  assert.ok(m, "could not find the kind CHECK constraint in db/002_signals.sql");
  const inSql = m[1].split(",").map(s => s.trim().replace(/^'|'$/g, ""));
  assert.deepEqual(inSql.sort(), [...SIGNAL_KINDS].sort());
});

test("the entry id CHECK constraint accepts every real id", () => {
  const m = SQL.match(/check \(entry_id ~ '([^']+)' and length\(entry_id\) between (\d+) and (\d+)\)/);
  assert.ok(m, "could not find the entry_id CHECK constraint");
  const re = new RegExp(m[1]);
  for (const id of ENTRY_IDS) {
    assert.match(id, re, id);
    assert.ok(id.length >= Number(m[2]) && id.length <= Number(m[3]),
      `${id} is ${id.length} characters, outside the constraint`);
  }
});

test("an id that is not in the registry is rejected", () => {
  const real = [...ENTRY_IDS][0];
  for (const bad of [
    "", "not-an-entry", `${real} `, ` ${real}`, `${real}'`, real.toUpperCase(),
    "../../etc/passwd", "%2e%2e", null, undefined, 42, {}, [], [real],
  ]) {
    assert.equal(isEntryId(bad), false, JSON.stringify(bad));
  }
});

test("a kind that is not one of the three is rejected", () => {
  for (const bad of ["", "needs_check", "NEEDS-CHECK", "spam", null, undefined, 0, {}, ["needs-check"]]) {
    assert.equal(isSignalKind(bad), false, JSON.stringify(bad));
  }
});

test("the generated block is sorted, so a reordered data file produces no diff", () => {
  const ids = [...ENTRY_IDS];
  assert.deepEqual(ids, [...ids].sort());
});
